# Generated by Django 3.2.5 on 2022-05-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='USERNAME_FIELD',
        ),
    ]
