# Generated by Django 3.2.5 on 2022-05-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_username_user_username_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='USERNAME_FIELD',
            new_name='username',
        ),
    ]
