# Generated by Django 3.2.5 on 2022-05-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_username_field_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
