# Generated by Django 3.2.5 on 2022-05-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_students', '0002_auto_20220520_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student'},
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.BooleanField(default=True, max_length=10),
        ),
    ]
