# Generated by Django 3.2.5 on 2022-05-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_students', '0003_auto_20220521_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='students',
            name='level',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
