# Generated by Django 3.2.5 on 2022-05-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='For General Programs', max_length=125)),
                ('content', models.TextField()),
                ('important', models.BooleanField(default=False)),
            ],
        ),
    ]
